### DISCUSSION TITLE
🚀 Dump Script Parsing Details

### DISCUSSION THREAD

**Discussion by AyhamAl-Ali** [SkriptLang/Skript#4926] [Suggestions]
# 🚀 Dump Script Parsing Details

An idea that LimeGlass originally suggested and opened my mind about it more, here I am suggesting my personal proposal for it to keep this idea in mind for the team

When reporting bugs, skript developers usually have to debug the reporter's script/scenario with specific environemnt which in many cases it can be a bit painful and many steps needed to be done therefore this proposal comes to rescue (for many many cases)

Adding a script parsing dump/debug file yml/txt/log/json? (my current proposal is in yml format)
The user can simply do `/sk debug/dump <script> [line] [verbosity]` then a file will be generated showing details of each line when parsed
- `[line]` optional argument can be specified to only debug a specific line that you are suspecting
- `[verbosity]` optional argument to quickly force specific verbosity level in-command

### Example report 

```yml
# Script: test.sk
# Date: 07/20/2022 10:06 PM
# ** Info from /sk info **

Line 31: "set tab list header of {_p} to {_header::*}"
    - Parsing time: 30ms
    Details:
        - Expr: "tab list header of {_p}"
            - Parsing time: 5ms
            - Return Type: String.class
            - Is Single: false
            - Expr: "{_p}"
                - Parsing time: 5ms
                - Return Type: Player.class
                - Is Single: true
        - Expr: "{_headers::*}" # can event have more debug info
            - Parse time: 20ms
            - Return Type: Variable.class
            - Is Single: false
```

The example above is very detailed and that's why this feature probably needs to comply to verbosity options, either its own verbosity option or the current debug verbosity option in config.sk

This way when trying to find what's went wrong with issues will mostly be easier to find for the dev team and the users.

Ideas are welcome.
