### ISSUE TITLE
Random Colouring Of Boots

### ISSUE THREAD

**Issue by redstonerblast** [SkriptLang/Skript#2144]
The Code Below Is Supposed To Make The Players Boots Into A Random Color, I Finally Got To The Point Of No Errors But It Still Has No Effect On The Boots...
```
options:
	rmi: 0
	rma: 255
	gmi: 0
	gma: 255
	bmi: 0
	bma: 255
	rtol: 0
	gtol: 0
	btol: 0

Command /soul:
    description: Colours Soul
    usage: /soul
    aliases: coloursoul, heart, soulc
    permission: soul.use
    trigger:
        message "&8[&7Soul&8] &6Colouring Soul..."
        set {rtol} to random integer from {rmi} to {rmx}
        set {gtol} to random integer from {gmi} to {gmx}
        set {btol} to random integer from {bmi} to {bmx}
        wait 10 tick
        dye player's shoe ({rtol}, {gtol}, {btol})
```
