### ISSUE TITLE
[feature] An official way to download addons

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#3141]
## Description

One thing that probably everyone will agree is we can't make anything outside of Minecraft with Skript, like we can't manage files (create, delete, move...), we can't make a discord bot and a lot of more!

But, something exists for that: addons!

Maybe it could be a good idea to have an official way to download and manages addons directly included in Skript.

What I was thinking is a way like that:

**Configuration file:**

```yaml
MyAddon:
    url: "https://github.com/MyAuthor/MyAddon/releases/download/version-a/MyAddon.jar"
    version: 0.1.0
MySecondAddon:
    url: "https://github.com/MySecondAuthor/MyAddon/releases/download/version-b/MySecondAddon.jar"
    version: 3.2.1
```

**Commandes:**

```
/sk addons add <name> <url>
/sk addons remove <name>
/sk addons edit <name> <url>
/sk addons update <name>
/sk addons download <name>
```

## Why

The good thing using this method is we can change the link where Skript can download addon, so we're sure that every addons have a up to date source code.
Another good thing is a lot of people use some addons pack, and in these packs, there are sometimes deprecated addons. So using this method, we avoid that.

What do you guys think about it?
