### ISSUE TITLE
Script Dependences

### ISSUE THREAD

**Issue by Ryan12439** [SkriptLang/Skript#3963]
Suggestion:

Add the ability to add dependences to your script so that it will not start if those dependences aren't existing/installed. It also won't start that script until all dependences are parsed and ready.

Something similar to:
```
depend:
  addons:
    - mongosk
  scripts:
    - script1.sk
    - script2.sk
```
