### ISSUE TITLE
Better Options

### ISSUE THREAD

**Issue by quick007** [SkriptLang/Skript#4032]
would be cool if we could do like
```
options:
    price:
        apple: 1000
        orange: 100
    among:
        us: lSkyblock
        sus: imposterrrr
```

you would reference options like `{@price.apple}`. This would make it easier for scripts with lots of configurations to work.
